### ISSUE TITLE
Have you been able to POST/PATCH changes back to redmine

### ISSUE THREAD

**Issue by larowlan** [crownloyal/redstone#7]
We're building some tools on top of redmine and haven't had any luck 

Seems redmine doesn't support CORS (404 for any OPTIONS request) and jsonp attempts to update aren't yielding much.

**Comment by crownloyal** [comment]
Greetings!

This application is just read-only and doesn't do any PUT requests whatsoever.
But I'll play around with it as that would be a logical next step.

I'll let you know my findings -- JSONP by itself was fairly reliable from my experience.

**Comment by larowlan** [comment]
Thanks for confirming
